### ISSUE TITLE
Compiling with gcc (mingw)

### ISSUE THREAD

**Issue by jope12** [robdunn4/QSpice#2]
Hi,

in your "CBlockTemplates.pdf" you write: 
"I convinced it to compile/link for 32-bit DLLs but sometimes – not always – QSpice doesn’t like the results and coughs up something like “unable to load [DLL]” and doesn’t provide any helpful details."

Can you give an example where this error happens?

**Comment by robdunn4** [comment]
Hi, Jope.

 

No, I didn’t save specific examples.  It went like this:

 

I got the initial setup/compile/link working for a simple DLL with only an evaluation function working.  Then, when I added MaxExtTimeStep() and/or Trunc() functions, I got clean compiles.  QSpice would load/run some combinations but not others.  The problem was consistent for a given code, i.e, could recompile and consistently load or not load.

 

Are you using MinGW successfully?

 

--robert

 

From: jope12 ***@***.***> 
Sent: Sunday, November 12, 2023 4:12 PM
To: robdunn4/QSpice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [robdunn4/QSpice] Compiling with gcc (mingw) (Issue #2)

 

Hi,

in your "CBlockTemplates.pdf" you write:
"I convinced it to compile/link for 32-bit DLLs but sometimes – not always – QSpice doesn’t like the results and coughs up something like “unable to load [DLL]” and doesn’t provide any helpful details."

Can you give an example where this error happens?

**Comment by jope12** [comment]
All of your examples work. Minor issues:  Some source files were missing a _#include \<exception\>_, and the Digital Mars msleep() has to be replaced with Sleep() (needed header: \<windows.h\>).

**Comment by robdunn4** [comment]
Thanks.  I started looking at it again (before I saw your last message).  May be the difference between gcc and g++.  What compile/link options are you using?

**Comment by jope12** [comment]
E.g.: 
g++ -O2 WavOut.cpp -static -shared -o wavout.dll

You don't have to use '-static', but its lack is possibly the reason for your problems. The correct 32-bit DLLs have to be loaded. Either put them all in the folder of your qspice DLL or use '-static' or pray for the best.

**Comment by robdunn4** [comment]
Oh, I bet that's it (-static)!  Will let you know.  Thanks!

**Comment by robdunn4** [comment]
OK, you're my hero.  I thought that it must not linking statically -- how else would QSpice reject it at load?  But gcc worked (at least sometimes) so I thought that it was something else and hadn't chased down the linker option.

Are you using VS Code for the QSpice development?  If so, I have another question.

Thanks again.

**Comment by jope12** [comment]
No VS Code. Gvim & make.

**Comment by robdunn4** [comment]
Oh, well, I guess I can't expect you to solve all of my problems.  Thanks for the help.
